from back_end import *
telaInicio()
# Criar IF para validar os inputs CPF (Validar CPF e input (Somente INT)) | Cadastrar Cliente ✅
# Criar IF para validar inputs comodos (Somente INT) | Cadastrar Imovel ✅
# Criar IF para sair do atribuir cliente ao imovel

#TESTES:
#Cadastrar Adm ✅
#Logar adm ✅
#Listar Imoveis ✅
#Cadastrar Imovel ✅
#Listar Cliente ✅
#Cadastrar Cliente ✅ 
#Remover Imovel ✅
#Remover ADM✅
#Remover Cliente ✅
#Remover Pagamento 🔄️
#Listar Pagamentos                  | Fazendo
#Registrar Pagamento                | Fazendo
#Listar Imoveis Ocupados | INNERJOIN fk_tbl_imovel_id_cliente NOT LIKE = Null | Fazendo